/** Parse a Directus CSV tag field into a string array. */
export function parseTags(value: string | null | undefined): string[] {
  if (!value) return [];
  return value.split(",").map((t) => t.trim()).filter(Boolean);
}

export const ALL_TAGS: string[] = [
  // --- TOOLS & HARDWARE ---
  "Hand Tools",
  "Power Tools",
  "Garden Tools",
  "Ladders & Scaffolding",
  "Welding Equipment",
  "Measuring & Layout Tools",
  "Safety Equipment",
  "Workbench & Storage",
  "Hammer",
  "Screwdriver Set",
  "Wrench Set",
  "Socket Set",
  "Pliers",
  "Utility Knife",
  "Chisel Set",
  "Hand Saw",
  "Drill",
  "Impact Driver",
  "Circular Saw",
  "Jigsaw",
  "Table Saw",
  "Miter Saw",
  "Band Saw",
  "Chainsaw",
  "Reciprocating Saw",
  "Oscillating Tool",
  "Belt Sander",
  "Angle Grinder",
  "Nail Gun",
  "Air Compressor",
  "Pressure Washer",
  "Heat Gun",
  "Soldering Iron",
  "Welder",
  "Generator",
  "Multimeter",
  "Stud Finder",
  "Level",
  "Tape Measure",
  "Laser Level",
  "Pipe Wrench",
  "Bolt Cutters",
  "Hacksaw",
  "Wire Stripper",
  "Crimping Tool",
  "Torque Wrench",
  "Pry Bar",

  // --- FARM & YARD EQUIPMENT ---
  "Tractor",
  "Riding Mower",
  "Push Mower",
  "Rototiller",
  "Tiller",
  "Snow Blower",
  "Leaf Blower",
  "Leaf Blower Backpack",
  "Brush Hog",
  "Spreader",
  "Sprayer",
  "Log Splitter",
  "Wood Chipper",
  "ATV",
  "UTV",
  "Golf Cart",
  "Trailer",
  "Utility Trailer",
  "Cargo Trailer",
  "Horse Trailer",
  "Dump Trailer",
  "Wheelbarrow",
  "Garden Cart",

  // --- FOOD & PRODUCE ---
  "Fresh Produce",
  "Preserved Foods",
  "Honey & Bee Products",
  "Eggs & Dairy",
  "Baked Goods",
  "Homemade Meals",
  "Herbs & Spices",
  "Seeds & Starts",
  "Tomatoes",
  "Zucchini",
  "Cucumbers",
  "Peppers",
  "Garlic",
  "Onions",
  "Potatoes",
  "Sweet Corn",
  "Eggs",
  "Honey",
  "Jam & Jelly",
  "Sourdough Starter",
  "Sourdough Bread",
  "Kombucha",
  "Salsa",
  "Pickles",
  "Hot Sauce",
  "Maple Syrup",
  "Mushrooms",
  "Microgreens",
  "Apple Cider",
  "Fruit Preserves",
  "Fermented Foods",
  "Bone Broth",
  "Lard & Tallow",
  "Raw Milk",
  "Goat Milk",
  "Cheese",
  "Butter",
  "Sprouts",
  "Fruit Trees",
  "Berry Bushes",
  "Herb Starts",

  // --- KITCHEN ---
  "Cookware",
  "Bakeware",
  "Kitchen Appliances",
  "Canning Equipment",
  "Coffee & Tea Equipment",
  "Knives & Cutlery",
  "Cast Iron Skillet",
  "Dutch Oven",
  "Stand Mixer",
  "Instant Pot",
  "Pressure Cooker",
  "Dehydrator",
  "Food Processor",
  "Blender",
  "Bread Machine",
  "Pasta Maker",
  "Wok",
  "Pressure Canner",
  "Water Bath Canner",
  "Grain Mill",
  "Juicer",
  "Ice Cream Maker",
  "Fermentation Crocks",
  "Mason Jars",
  "Vacuum Sealer",
  "Smoker",
  "Outdoor Grill",
  "Pizza Stone",
  "Mandoline",

  // --- CLOTHING & ACCESSORIES ---
  "Men's Clothing",
  "Women's Clothing",
  "Children's Clothing",
  "Shoes & Boots",
  "Outerwear",
  "Work & Safety Gear",
  "Hats & Accessories",
  "Rain Gear",
  "Winter Coat",
  "Work Boots",
  "Rubber Boots",
  "Coveralls",
  "Hi-Vis Vest",
  "Gloves",
  "Wool Socks",
  "Denim",
  "Flannel Shirts",

  // --- FURNITURE & HOME ---
  "Living Room Furniture",
  "Bedroom Furniture",
  "Outdoor Furniture",
  "Storage & Shelving",
  "Lighting",
  "Rugs & Textiles",
  "Bedding & Linens",
  "Home Decor",
  "Couch",
  "Dining Table",
  "Dresser",
  "Bookshelf",
  "Desk",
  "Office Chair",
  "Bed Frame",
  "Mattress",
  "Filing Cabinet",
  "TV Stand",
  "Coffee Table",
  "Patio Set",
  "Adirondack Chair",
  "Fire Pit",
  "Hammock",
  "Shelving Unit",
  "Workbench",
  "Safe",
  "Wood Stove",
  "Pellet Stove",
  "Propane Heater",
  "Ceiling Fan",
  "Window AC Unit",

  // --- ELECTRONICS & TECH ---
  "Computers & Laptops",
  "Phones & Tablets",
  "Audio Equipment",
  "Cameras",
  "TVs & Displays",
  "Gaming Equipment",
  "Smart Home Devices",
  "Cables & Accessories",
  "Laptop",
  "Desktop Computer",
  "Monitor",
  "Tablet",
  "Smartphone",
  "Keyboard & Mouse",
  "Speakers",
  "Headphones",
  "Projector",
  "TV",
  "Game Console",
  "Nintendo Switch",
  "PlayStation",
  "Xbox",
  "DSLR Camera",
  "Mirrorless Camera",
  "GoPro",
  "Drone",
  "Ham Radio",
  "CB Radio",
  "Two-Way Radios",
  "Solar Panel",
  "Battery Bank",
  "Inverter",
  "Raspberry Pi",
  "Arduino",

  // --- BOOKS, MEDIA & GAMES ---
  "Fiction Books",
  "Non-Fiction Books",
  "Textbooks",
  "DVDs & Blu-rays",
  "Vinyl Records",
  "Board Games",
  "Video Games",
  "Musical Instruments",
  "Cookbooks",
  "Field Guides",
  "Repair Manuals",
  "Homesteading Books",
  "Children's Books",
  "Comic Books",
  "Reference Books",
  "Puzzles",

  // --- GARDEN & OUTDOORS ---
  "Seeds & Bulbs",
  "Plants & Seedlings",
  "Soil & Compost",
  "Pots & Planters",
  "Lawn Equipment",
  "Fencing & Edging",
  "Raised Bed",
  "Greenhouse",
  "Cold Frame",
  "Hoop House",
  "Compost Bin",
  "Rain Barrel",
  "Chicken Coop",
  "Rabbit Hutch",
  "Beehive",
  "Irrigation System",
  "Garden Hose",
  "Sprinkler",
  "Fence Posts",
  "Chicken Wire",
  "T-Posts",
  "Field Fencing",
  "Grow Lights",
  "Seed Packets",
  "Perennials",
  "Bulbs",
  "Mulch",
  "Gravel",
  "Topsoil",
  "Compost",
  "Manure",

  // --- LIVESTOCK & ANIMALS ---
  "Livestock Feed",
  "Hay",
  "Straw",
  "Animal Housing",
  "Fencing for Livestock",
  "Water Trough",
  "Feed Bins",
  "Saddle & Tack",
  "Dog Food",
  "Pet Supplies",
  "Aquarium",
  "Fish Tank Equipment",

  // --- SPORTS & RECREATION ---
  "Bicycles",
  "Camping & Hiking Gear",
  "Fishing Equipment",
  "Exercise Equipment",
  "Team Sports Equipment",
  "Water Sports",
  "Winter Sports",
  "Climbing Gear",
  "Mountain Bike",
  "Road Bike",
  "BMX Bike",
  "Kayak",
  "Canoe",
  "Paddleboard",
  "Tent",
  "Sleeping Bag",
  "Backpack",
  "Trekking Poles",
  "Fishing Rod",
  "Tackle Box",
  "Hunting Gear",
  "Archery Equipment",
  "Bow",
  "Crossbow",
  "Golf Clubs",
  "Tennis Racket",
  "Skis",
  "Snowboard",
  "Snowshoes",
  "Ice Skates",
  "Weights",
  "Barbell",
  "Kettlebell",
  "Treadmill",
  "Stationary Bike",
  "Rowing Machine",
  "Yoga Mat",
  "Canteen & Water Filter",
  "Binoculars",
  "Spotting Scope",
  "Trail Camera",
  "Life Jacket",

  // --- KIDS & BABY ---
  "Baby Furniture",
  "Strollers & Car Seats",
  "Toys & Games",
  "Baby Clothing",
  "Educational Materials",
  "Crib",
  "Bassinet",
  "High Chair",
  "Baby Monitor",
  "Baby Swing",
  "Play Mat",
  "Bounce House",
  "Scooter",
  "Skateboard",
  "Legos",
  "Tricycle",
  "Balance Bike",
  "Swing Set",
  "Trampoline",

  // --- VEHICLES & TRANSPORT ---
  "Car Parts & Accessories",
  "Tires & Wheels",
  "Bike Parts",
  "Boat Equipment",
  "Car Battery",
  "Jump Starter",
  "Car Cover",
  "Roof Rack",
  "Hitch",
  "Winch",
  "Toolbox (Truck)",
  "Motorcycle",
  "Dirt Bike",
  "Snowmobile",
  "Boat Motor",
  "Canoe Paddle",
  "Kayak Paddle",

  // --- BUILDING MATERIALS ---
  "Lumber & Wood",
  "Paint & Finishes",
  "Flooring",
  "Plumbing Supplies",
  "Electrical Supplies",
  "Hardware & Fasteners",
  "Plywood",
  "OSB",
  "Drywall",
  "Concrete Block",
  "Brick",
  "Metal Roofing",
  "Shingles",
  "PVC Pipe",
  "Copper Pipe",
  "Electrical Wire",
  "Conduit",
  "Insulation",
  "Spray Foam",
  "Thinset & Grout",
  "Tile",
  "Hardwood Flooring",
  "Laminate Flooring",
  "Deck Boards",
  "Fence Pickets",
  "Rebar",
  "Concrete Mix",
  "Sand",
  "Caulk & Sealant",
  "Door",
  "Window",
  "Roofing Tin",

  // --- TRADE SKILLS ---
  "Carpentry & Woodworking",
  "Plumbing",
  "Electrical Work",
  "HVAC",
  "Roofing",
  "Masonry & Concrete",
  "Welding & Fabrication",
  "Painting & Finishing",
  "Landscaping",
  "Tree Work",
  "Vehicle Repair",
  "Appliance Repair",
  "Computer Repair",
  "Phone Repair",
  "Sewing & Alterations",
  "Knitting & Crocheting",
  "Leatherworking",
  "Upholstery",
  "Tile Installation",
  "Drywall Repair",
  "Fence Building",
  "Deck Building",
  "Cabinet Making",
  "Furniture Restoration",
  "Auto Body Work",
  "Engine Repair",
  "Small Engine Repair",
  "Tractor Repair",
  "Knife Sharpening",
  "Chainsaw Sharpening",
  "Boot Resoling",
  "Watch Repair",
  "Jewelry Making",
  "Blacksmithing",
  "Pottery",
  "Woodturning",
  "Screen Printing",
  "Embroidery",
  "Quilting",
  "Soap Making",
  "Candle Making",
  "Brewing",
  "Winemaking",
  "Cheese Making",
  "Butchering",
  "Hunting & Trapping",
  "Foraging",
  "Taxidermy",

  // --- FOOD SKILLS ---
  "Cooking & Meal Prep",
  "Baking & Pastry",
  "Canning & Food Preservation",
  "Beekeeping",
  "Farming & Agriculture",
  "Bread Baking",
  "Sourdough",
  "Fermentation",
  "Charcuterie",
  "Smoking & Curing",
  "Dehydrating",
  "Butcher Skills",
  "Wild Game Processing",

  // --- CREATIVE & PROFESSIONAL SKILLS ---
  "Graphic Design",
  "Web Development",
  "Photography",
  "Videography",
  "Writing & Editing",
  "Translation",
  "Accounting & Bookkeeping",
  "Social Media",
  "Legal Advice",
  "Administrative & Office",
  "Logo Design",
  "Video Editing",
  "Podcast Editing",
  "3D Printing",
  "CNC Routing",
  "Laser Cutting",

  // --- TEACHING & COACHING ---
  "Music Lessons",
  "Art & Drawing",
  "Yoga & Fitness Training",
  "Martial Arts",
  "Dance Lessons",
  "Language Tutoring",
  "Math & Science Tutoring",
  "Test Prep",
  "Homesteading Skills",
  "First Aid & CPR",
  "Firearms Safety",
  "Ham Radio Licensing",
  "Navigation & Orienteering",
  "Wilderness Survival",

  // --- SERVICES ---
  "Childcare & Babysitting",
  "Elder Care",
  "Pet Sitting",
  "Dog Walking",
  "House Cleaning",
  "Laundry & Ironing",
  "Lawn Mowing",
  "Snow Removal",
  "Moving & Hauling",
  "Truck & Trailer Use",
  "Grocery Shopping",
  "Meal Delivery",
  "Event Help",
  "DJ & Music",
  "Notary Services",
  "Firewood Delivery",
  "Firewood Splitting",
  "Gutter Cleaning",
  "Window Washing",
  "Pressure Washing",
  "Junk Removal",
  "Stump Grinding",
  "Brush Clearing",
  "Well Maintenance",
  "Septic Service",
  "Water Testing",
  "House Sitting",
  "Property Watching",
  "Security Check-ins",
];
